apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-nest
  namespace: coach
  labels:
    app: template-nest
spec:
  selector:
    matchLabels:
      app: template-nest
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: template-nest
    spec:
      containers:
        - name: template-nest
          image: //TODO HERE PUT DOCKER IMAGE LINK
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_ah/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: 8080
            - name: TYPEORM_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_CONNECTION
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_HOST
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_USERNAME
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_PASSWORD
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_DATABASE
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_PORT
            - name: TYPEORM_SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_SYNCHRONIZE
            - name: TYPEORM_LOGGING
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_LOGGING
            - name: TYPEORM_ENTITIES
              valueFrom:
                secretKeyRef:
                  name: typeorm_connection
                  key: TYPEORM_ENTITIES

